---
title: "Final project"
author: "Xueru Ma"
date: "06/04/2022"
output: pdf_document
---

---
title: "The Outbreak Of COVID-19: Accidental or Inevitable"
subtitle: "Trends of Coronavirus Cases in Toronto"
author: 
  - Xueru Ma
thanks: "Code and data are available at: https://github.com/maxueru001023/sta304_Final_paper"
output:
  bookdown::pdf_document2
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "COVID-19 has dramatically influenced the lifestyles of people all over the world in recent years and it seriously hindered the economic development of various countries. The dataset we used was extracted from the provincial Case & Contact Management System (CCM), being reported and managed by Toronto Public Health.  We analyzed the relationship between covid cases and factors like gender, age group, region, data, outbreak associated, source of infection. Our analysis provides an insight into the COVID-19 trends in the past two years in Toronto and the put forward a number of initiatives to avoid new outbreaks in the future. \\par\\textbf{keywords:} Covid-19, Toronto, gender, age, region, source of infection, outbreak associated"
toc: FALSE
bibliography: ref.bib 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction

As the focus in recent years, coronavirus has brought many risks and inconveniences to people's lives. Due to the easily transmissible characteristics of covid-19 and the potential complications it can bring, the government has been monitoring the local situation and managing the outbreak dynamically. When the outbreak was relatively severe, the government lockdown the city and advised residents to work from home and reduce mobility. When the pandemic is less intense, the government releases restrictions on the population and focuses on economic recovery.

Toronto Public Health is responding to an ongoing COVID-19 outbreak, in the context of an evolving global pandemic. This data set contains demographic, geographic, and severity information for all confirmed and probable cases reported to and managed by Toronto Public Health since the first case was reported in January 2020. This includes cases that are sporadic (occurring in the community) and outbreak-associated. The data are extracted from the provincial Case & Contact Management System (CCM).


# Data

## Data Source





# Model





# Results

# Discussion

## First discussion point


## Second discussion point

## Third discussion point

## Weaknesses and next steps


\newpage

\appendix

# Appendix {-}


# Additional details


\newpage


# References


